gtk/gtkcssnumbervalue.c: fix compilation if fenv.h is missing
../gtk/gtkcssnumbervalue.c:29:10: fatal error: fenv.h: No such file or directory
   29 | #include <fenv.h>
      |

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>